// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Command struct {
	ID        int64
	Name      string
	Command   string
	CreatedAt string
	UpdatedAt string
}

type Secret struct {
	ID        int64
	Key       string
	Value     string
	CreatedAt string
	UpdatedAt string
}
