// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
)

type Command struct {
	ID          int64
	Name        string
	Command     string
	Description string
	Parameters  json.RawMessage
	CreatedAt   string
	UpdatedAt   string
}

type Secret struct {
	ID          int64
	Key         string
	Value       string
	Description string
	CreatedAt   string
	UpdatedAt   string
}
